import React from "react";
import type { Metadata } from 'next';

// Fonts
import { Anonymous_Pro } from 'next/font/google';

// Styles
import './styles/globals.css';

const anonymousPro = Anonymous_Pro({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'InLocate',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={anonymousPro.className}>{children}</body>
    </html>
  )
}
